"""create user_anime_relationships table

Revision ID: 358245db7a4b
Revises: aab09fbc2580
Create Date: 2026-02-27 02:35:27.163058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358245db7a4b'
down_revision: Union[str, Sequence[str], None] = 'c8b7aaaf4038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_anime_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anime_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('watching', 'completed', 'dropped', 'plan_to_watch', 'on_hold', name='watchstatus'), nullable=False),
    sa.Column('score_story', sa.Integer(), nullable=True),
    sa.Column('score_art', sa.Integer(), nullable=True),
    sa.Column('score_sound', sa.Integer(), nullable=True),
    sa.Column('score_characters', sa.Integer(), nullable=True),
    sa.Column('score_enjoyment', sa.Integer(), nullable=True),
    sa.Column('computed_overall', sa.Integer(), nullable=True),
    sa.Column('rewatch_count', sa.Integer(), nullable=True),
    sa.Column('rewatch_score', sa.Integer(), nullable=True),
    sa.Column('currently_watching_ep', sa.Integer(), nullable=True),
    sa.Column('date_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_anime_relationships_anime_id'), 'user_anime_relationships', ['anime_id'], unique=False)
    op.create_index(op.f('ix_user_anime_relationships_user_id'), 'user_anime_relationships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_anime_relationships_user_id'), table_name='user_anime_relationships')
    op.drop_index(op.f('ix_user_anime_relationships_anime_id'), table_name='user_anime_relationships')
    op.drop_table('user_anime_relationships')
    # ### end Alembic commands ###
