"""add taste_vector to users

Revision ID: 578a6aad5494
Revises: a547f168c01b
Create Date: 2026-04-06 05:50:15.454995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '578a6aad5494'
down_revision: Union[str, Sequence[str], None] = 'a547f168c01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension — required before creating vector columns
    # Already enabled in Supabase production. Needed for local Docker.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('users', sa.Column('taste_vector', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=True))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'taste_vector')
    # ### end Alembic commands ###
