"""add mood_tags and user_anime_mood_tags tables

Revision ID: 8ecbd11bacc8
Revises: a0c1890c4c6d
Create Date: 2026-03-04 05:36:18.672707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecbd11bacc8'
down_revision: Union[str, Sequence[str], None] = 'a0c1890c4c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_suggested', sa.Boolean(), nullable=True),
    sa.Column('parent_mood_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_mood_id'], ['mood_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_anime_mood_tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anime_id', sa.UUID(), nullable=False),
    sa.Column('mood_tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mood_tag_id'], ['mood_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'anime_id', 'mood_tag_id')
    )
    op.create_index(op.f('ix_user_anime_mood_tags_anime_id'), 'user_anime_mood_tags', ['anime_id'], unique=False)
    op.alter_column('user_anime_relationships', 'computed_overall',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'user_anime_relationships', ['user_id', 'anime_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_anime_relationships', type_='unique')
    op.alter_column('user_anime_relationships', 'computed_overall',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_anime_mood_tags_anime_id'), table_name='user_anime_mood_tags')
    op.drop_table('user_anime_mood_tags')
    op.drop_table('mood_tags')
    # ### end Alembic commands ###
