"""add mal_id to anime table

Revision ID: a0c1890c4c6d
Revises: 358245db7a4b
Create Date: 2026-03-01 00:41:36.251139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0c1890c4c6d'
down_revision: Union[str, Sequence[str], None] = '358245db7a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_english', sa.String(length=500), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('cached_vibe_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('average_score', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_anilist_id'), 'anime', ['anilist_id'], unique=True)
    op.create_index(op.f('ix_anime_mal_id'), 'anime', ['mal_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_anime_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anime_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('watching', 'completed', 'dropped', 'plan_to_watch', 'on_hold', name='watchstatus'), nullable=False),
    sa.Column('score_story', sa.Integer(), nullable=True),
    sa.Column('score_art', sa.Integer(), nullable=True),
    sa.Column('score_sound', sa.Integer(), nullable=True),
    sa.Column('score_characters', sa.Integer(), nullable=True),
    sa.Column('score_enjoyment', sa.Integer(), nullable=True),
    sa.Column('computed_overall', sa.Integer(), nullable=True),
    sa.Column('rewatch_count', sa.Integer(), nullable=True),
    sa.Column('rewatch_score', sa.Integer(), nullable=True),
    sa.Column('currently_watching_ep', sa.Integer(), nullable=True),
    sa.Column('date_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_anime_relationships_anime_id'), 'user_anime_relationships', ['anime_id'], unique=False)
    op.create_index(op.f('ix_user_anime_relationships_user_id'), 'user_anime_relationships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_anime_relationships_user_id'), table_name='user_anime_relationships')
    op.drop_index(op.f('ix_user_anime_relationships_anime_id'), table_name='user_anime_relationships')
    op.drop_table('user_anime_relationships')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_anime_mal_id'), table_name='anime')
    op.drop_index(op.f('ix_anime_anilist_id'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
