"""create anime table

Revision ID: c8b7aaaf4038
Revises: 704d2050a91e
Create Date: 2026-02-26 03:07:44.714997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8b7aaaf4038'
down_revision: Union[str, Sequence[str], None] = '704d2050a91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_english', sa.String(length=500), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('cached_vibe_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('average_score', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_anilist_id'), 'anime', ['anilist_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anime_anilist_id'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
